"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
pairingmessage.proto"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _RoleType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _RoleTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_RoleType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ROLE_TYPE_UNKNOWN: _RoleType.ValueType  # 0
    ROLE_TYPE_INPUT: _RoleType.ValueType  # 1
    ROLE_TYPE_OUTPUT: _RoleType.ValueType  # 2
    UNRECOGNIZED: _RoleType.ValueType  # -1

class RoleType(_RoleType, metaclass=_RoleTypeEnumTypeWrapper): ...

ROLE_TYPE_UNKNOWN: RoleType.ValueType  # 0
ROLE_TYPE_INPUT: RoleType.ValueType  # 1
ROLE_TYPE_OUTPUT: RoleType.ValueType  # 2
UNRECOGNIZED: RoleType.ValueType  # -1
global___RoleType = RoleType

@typing_extensions.final
class PairingRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CLIENT_NAME_FIELD_NUMBER: builtins.int
    SERVICE_NAME_FIELD_NUMBER: builtins.int
    client_name: builtins.str
    service_name: builtins.str
    def __init__(
        self,
        *,
        client_name: builtins.str = ...,
        service_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["client_name", b"client_name", "service_name", b"service_name"]) -> None: ...

global___PairingRequest = PairingRequest

@typing_extensions.final
class PairingRequestAck(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERVER_NAME_FIELD_NUMBER: builtins.int
    server_name: builtins.str
    def __init__(
        self,
        *,
        server_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["server_name", b"server_name"]) -> None: ...

global___PairingRequestAck = PairingRequestAck

@typing_extensions.final
class PairingEncoding(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _EncodingType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _EncodingTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[PairingEncoding._EncodingType.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        ENCODING_TYPE_UNKNOWN: PairingEncoding._EncodingType.ValueType  # 0
        ENCODING_TYPE_ALPHANUMERIC: PairingEncoding._EncodingType.ValueType  # 1
        ENCODING_TYPE_NUMERIC: PairingEncoding._EncodingType.ValueType  # 2
        ENCODING_TYPE_HEXADECIMAL: PairingEncoding._EncodingType.ValueType  # 3
        ENCODING_TYPE_QRCODE: PairingEncoding._EncodingType.ValueType  # 4
        UNRECOGNIZED: PairingEncoding._EncodingType.ValueType  # -1

    class EncodingType(_EncodingType, metaclass=_EncodingTypeEnumTypeWrapper): ...
    ENCODING_TYPE_UNKNOWN: PairingEncoding.EncodingType.ValueType  # 0
    ENCODING_TYPE_ALPHANUMERIC: PairingEncoding.EncodingType.ValueType  # 1
    ENCODING_TYPE_NUMERIC: PairingEncoding.EncodingType.ValueType  # 2
    ENCODING_TYPE_HEXADECIMAL: PairingEncoding.EncodingType.ValueType  # 3
    ENCODING_TYPE_QRCODE: PairingEncoding.EncodingType.ValueType  # 4
    UNRECOGNIZED: PairingEncoding.EncodingType.ValueType  # -1

    TYPE_FIELD_NUMBER: builtins.int
    SYMBOL_LENGTH_FIELD_NUMBER: builtins.int
    type: global___PairingEncoding.EncodingType.ValueType
    symbol_length: builtins.int
    def __init__(
        self,
        *,
        type: global___PairingEncoding.EncodingType.ValueType = ...,
        symbol_length: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["symbol_length", b"symbol_length", "type", b"type"]) -> None: ...

global___PairingEncoding = PairingEncoding

@typing_extensions.final
class PairingOption(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INPUT_ENCODINGS_FIELD_NUMBER: builtins.int
    OUTPUT_ENCODINGS_FIELD_NUMBER: builtins.int
    PREFERRED_ROLE_FIELD_NUMBER: builtins.int
    @property
    def input_encodings(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PairingEncoding]: ...
    @property
    def output_encodings(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PairingEncoding]: ...
    preferred_role: global___RoleType.ValueType
    def __init__(
        self,
        *,
        input_encodings: collections.abc.Iterable[global___PairingEncoding] | None = ...,
        output_encodings: collections.abc.Iterable[global___PairingEncoding] | None = ...,
        preferred_role: global___RoleType.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["input_encodings", b"input_encodings", "output_encodings", b"output_encodings", "preferred_role", b"preferred_role"]) -> None: ...

global___PairingOption = PairingOption

@typing_extensions.final
class PairingConfiguration(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENCODING_FIELD_NUMBER: builtins.int
    CLIENT_ROLE_FIELD_NUMBER: builtins.int
    @property
    def encoding(self) -> global___PairingEncoding: ...
    client_role: global___RoleType.ValueType
    def __init__(
        self,
        *,
        encoding: global___PairingEncoding | None = ...,
        client_role: global___RoleType.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["encoding", b"encoding"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["client_role", b"client_role", "encoding", b"encoding"]) -> None: ...

global___PairingConfiguration = PairingConfiguration

@typing_extensions.final
class PairingConfigurationAck(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___PairingConfigurationAck = PairingConfigurationAck

@typing_extensions.final
class PairingSecret(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECRET_FIELD_NUMBER: builtins.int
    secret: builtins.bytes
    def __init__(
        self,
        *,
        secret: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["secret", b"secret"]) -> None: ...

global___PairingSecret = PairingSecret

@typing_extensions.final
class PairingSecretAck(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECRET_FIELD_NUMBER: builtins.int
    secret: builtins.bytes
    def __init__(
        self,
        *,
        secret: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["secret", b"secret"]) -> None: ...

global___PairingSecretAck = PairingSecretAck

@typing_extensions.final
class PairingMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Status:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _StatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[PairingMessage._Status.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: PairingMessage._Status.ValueType  # 0
        STATUS_OK: PairingMessage._Status.ValueType  # 200
        STATUS_ERROR: PairingMessage._Status.ValueType  # 400
        STATUS_BAD_CONFIGURATION: PairingMessage._Status.ValueType  # 401
        STATUS_BAD_SECRET: PairingMessage._Status.ValueType  # 402
        UNRECOGNIZED: PairingMessage._Status.ValueType  # -1

    class Status(_Status, metaclass=_StatusEnumTypeWrapper): ...
    UNKNOWN: PairingMessage.Status.ValueType  # 0
    STATUS_OK: PairingMessage.Status.ValueType  # 200
    STATUS_ERROR: PairingMessage.Status.ValueType  # 400
    STATUS_BAD_CONFIGURATION: PairingMessage.Status.ValueType  # 401
    STATUS_BAD_SECRET: PairingMessage.Status.ValueType  # 402
    UNRECOGNIZED: PairingMessage.Status.ValueType  # -1

    PROTOCOL_VERSION_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    REQUEST_CASE_FIELD_NUMBER: builtins.int
    PAIRING_REQUEST_FIELD_NUMBER: builtins.int
    PAIRING_REQUEST_ACK_FIELD_NUMBER: builtins.int
    PAIRING_OPTION_FIELD_NUMBER: builtins.int
    PAIRING_CONFIGURATION_FIELD_NUMBER: builtins.int
    PAIRING_CONFIGURATION_ACK_FIELD_NUMBER: builtins.int
    PAIRING_SECRET_FIELD_NUMBER: builtins.int
    PAIRING_SECRET_ACK_FIELD_NUMBER: builtins.int
    protocol_version: builtins.int
    status: global___PairingMessage.Status.ValueType
    request_case: builtins.int
    @property
    def pairing_request(self) -> global___PairingRequest: ...
    @property
    def pairing_request_ack(self) -> global___PairingRequestAck: ...
    @property
    def pairing_option(self) -> global___PairingOption: ...
    @property
    def pairing_configuration(self) -> global___PairingConfiguration: ...
    @property
    def pairing_configuration_ack(self) -> global___PairingConfigurationAck: ...
    @property
    def pairing_secret(self) -> global___PairingSecret: ...
    @property
    def pairing_secret_ack(self) -> global___PairingSecretAck: ...
    def __init__(
        self,
        *,
        protocol_version: builtins.int = ...,
        status: global___PairingMessage.Status.ValueType = ...,
        request_case: builtins.int = ...,
        pairing_request: global___PairingRequest | None = ...,
        pairing_request_ack: global___PairingRequestAck | None = ...,
        pairing_option: global___PairingOption | None = ...,
        pairing_configuration: global___PairingConfiguration | None = ...,
        pairing_configuration_ack: global___PairingConfigurationAck | None = ...,
        pairing_secret: global___PairingSecret | None = ...,
        pairing_secret_ack: global___PairingSecretAck | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["pairing_configuration", b"pairing_configuration", "pairing_configuration_ack", b"pairing_configuration_ack", "pairing_option", b"pairing_option", "pairing_request", b"pairing_request", "pairing_request_ack", b"pairing_request_ack", "pairing_secret", b"pairing_secret", "pairing_secret_ack", b"pairing_secret_ack"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["pairing_configuration", b"pairing_configuration", "pairing_configuration_ack", b"pairing_configuration_ack", "pairing_option", b"pairing_option", "pairing_request", b"pairing_request", "pairing_request_ack", b"pairing_request_ack", "pairing_secret", b"pairing_secret", "pairing_secret_ack", b"pairing_secret_ack", "protocol_version", b"protocol_version", "request_case", b"request_case", "status", b"status"]) -> None: ...

global___PairingMessage = PairingMessage
